### ISSUE TITLE
first laptime delta's value (after resetting stopwatch) is buggy

### ISSUE THREAD

**Issue by thaaadek** [Klrfl/TellTime#1]
This bug seems like it was caused by the resetWatch function not resetting the previousLap.value in StopwatchView.vue.

How to reproduce:

- Go to the stopwatch page
- Start stopwatch
- make a few laps, then reset stopwatch
- make a few laps again
- The first lap delta will not match

**Comment by Klrfl** [comment]
Thank you for reporting this bug! It is already fixed in 0.1.0.
